# Manual-ish task listing to get a specified Java version from the Oracle site.
# Currently using this as the main task for Java, will use Role version if this is insufficient.

  - name: Ensure wget is on the target machine
    yum:
      name: wget
      state: latest

  # Detect presence of large download
  - name: Detect presence of java installation at {{java_name}}
    stat: path='{{java_name}}'
    register: java_archive_exists

  - name: Download Java
    get_url:
      url:     "{{download_url}}"
      dest:    "{{download_folder}}"
      headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    when: java_archive_exists.stat.exists == False

  - name: Unpack JDK tarball file from [{{java_archive}}] to [{{download_folder}}/{{java_extracted_archive}}]
    unarchive:
      src: "{{ java_archive }}"
      dest: "{{download_folder}}"
      owner: root
      group: root
      mode: "go-w"
      copy: no

  - name: Fix ownership [{{download_folder}}/{{java_extracted_archive}}]
    file: state=directory path={{download_folder}}/{{java_extracted_archive}} owner=root group=root recurse=yes

  - name: Make Java available for system - install to [/usr/bin/java] from [{{download_folder}}/{{java_extracted_archive}}/bin/java]
    command: 'alternatives --install "/usr/bin/java" "java" "{{download_folder}}/{{java_extracted_archive}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path={{java_archive}}
