## jruby
jrubyTmpDir: /tmp
jrubyDir: /opt
jrubyUrl: https://s3.amazonaws.com/jruby.org/downloads/9.1.8.0/jruby-bin-9.1.8.0.tar.gz
jrubyCompressedFile: jruby-bin-9.1.8.0.tar.gz
jrubyUnzipped: jruby-9.1.8.0
